services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
  spark-master:
    image: apache/spark:3.5.1
    ports:
      - "8080:8080" 
      - "7077:7077"
    stdin_open: true 
    tty: true       
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master

  spark-worker:
    image: apache/spark:3.5.1
    depends_on:
      - spark-master
    stdin_open: true
    tty: true
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077